[package]
name = "Insultinator5_0"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "insultinator_backend"

[dependencies]
clipboard = "0.5"  
enigo = "0.2.1"
pyo3 = { version = "0.17", features = ["extension-module"] }
